//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace LanSysWebGIS.WebMethodsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebMethodsService.WebMethodsServiceSoap")]
    public interface WebMethodsServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DeleteFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginDeleteFile(string path, System.AsyncCallback callback, object asyncState);
        
        string EndDeleteFile(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetDate(System.AsyncCallback callback, object asyncState);
        
        System.DateTime EndGetDate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AccessFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginAccessFile(string path, System.AsyncCallback callback, object asyncState);
        
        void EndAccessFile(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebMethodsServiceSoapChannel : LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.DateTime Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebMethodsServiceSoapClient : System.ServiceModel.ClientBase<LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap>, LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap {
        
        private BeginOperationDelegate onBeginDeleteFileDelegate;
        
        private EndOperationDelegate onEndDeleteFileDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteFileCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDateDelegate;
        
        private EndOperationDelegate onEndGetDateDelegate;
        
        private System.Threading.SendOrPostCallback onGetDateCompletedDelegate;
        
        private BeginOperationDelegate onBeginAccessFileDelegate;
        
        private EndOperationDelegate onEndAccessFileDelegate;
        
        private System.Threading.SendOrPostCallback onAccessFileCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WebMethodsServiceSoapClient() {
        }
        
        public WebMethodsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebMethodsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebMethodsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebMethodsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<DeleteFileCompletedEventArgs> DeleteFileCompleted;
        
        public event System.EventHandler<GetDateCompletedEventArgs> GetDateCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AccessFileCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap.BeginDeleteFile(string path, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteFile(path, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap.EndDeleteFile(System.IAsyncResult result) {
            return base.Channel.EndDeleteFile(result);
        }
        
        private System.IAsyncResult OnBeginDeleteFile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string path = ((string)(inValues[0]));
            return ((LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap)(this)).BeginDeleteFile(path, callback, asyncState);
        }
        
        private object[] OnEndDeleteFile(System.IAsyncResult result) {
            string retVal = ((LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap)(this)).EndDeleteFile(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteFileCompleted(object state) {
            if ((this.DeleteFileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteFileCompleted(this, new DeleteFileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteFileAsync(string path) {
            this.DeleteFileAsync(path, null);
        }
        
        public void DeleteFileAsync(string path, object userState) {
            if ((this.onBeginDeleteFileDelegate == null)) {
                this.onBeginDeleteFileDelegate = new BeginOperationDelegate(this.OnBeginDeleteFile);
            }
            if ((this.onEndDeleteFileDelegate == null)) {
                this.onEndDeleteFileDelegate = new EndOperationDelegate(this.OnEndDeleteFile);
            }
            if ((this.onDeleteFileCompletedDelegate == null)) {
                this.onDeleteFileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteFileCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteFileDelegate, new object[] {
                        path}, this.onEndDeleteFileDelegate, this.onDeleteFileCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap.BeginGetDate(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDate(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.DateTime LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap.EndGetDate(System.IAsyncResult result) {
            return base.Channel.EndGetDate(result);
        }
        
        private System.IAsyncResult OnBeginGetDate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap)(this)).BeginGetDate(callback, asyncState);
        }
        
        private object[] OnEndGetDate(System.IAsyncResult result) {
            System.DateTime retVal = ((LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap)(this)).EndGetDate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDateCompleted(object state) {
            if ((this.GetDateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDateCompleted(this, new GetDateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDateAsync() {
            this.GetDateAsync(null);
        }
        
        public void GetDateAsync(object userState) {
            if ((this.onBeginGetDateDelegate == null)) {
                this.onBeginGetDateDelegate = new BeginOperationDelegate(this.OnBeginGetDate);
            }
            if ((this.onEndGetDateDelegate == null)) {
                this.onEndGetDateDelegate = new EndOperationDelegate(this.OnEndGetDate);
            }
            if ((this.onGetDateCompletedDelegate == null)) {
                this.onGetDateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDateCompleted);
            }
            base.InvokeAsync(this.onBeginGetDateDelegate, null, this.onEndGetDateDelegate, this.onGetDateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap.BeginAccessFile(string path, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAccessFile(path, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap.EndAccessFile(System.IAsyncResult result) {
            base.Channel.EndAccessFile(result);
        }
        
        private System.IAsyncResult OnBeginAccessFile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string path = ((string)(inValues[0]));
            return ((LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap)(this)).BeginAccessFile(path, callback, asyncState);
        }
        
        private object[] OnEndAccessFile(System.IAsyncResult result) {
            ((LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap)(this)).EndAccessFile(result);
            return null;
        }
        
        private void OnAccessFileCompleted(object state) {
            if ((this.AccessFileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AccessFileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AccessFileAsync(string path) {
            this.AccessFileAsync(path, null);
        }
        
        public void AccessFileAsync(string path, object userState) {
            if ((this.onBeginAccessFileDelegate == null)) {
                this.onBeginAccessFileDelegate = new BeginOperationDelegate(this.OnBeginAccessFile);
            }
            if ((this.onEndAccessFileDelegate == null)) {
                this.onEndAccessFileDelegate = new EndOperationDelegate(this.OnEndAccessFile);
            }
            if ((this.onAccessFileCompletedDelegate == null)) {
                this.onAccessFileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAccessFileCompleted);
            }
            base.InvokeAsync(this.onBeginAccessFileDelegate, new object[] {
                        path}, this.onEndAccessFileDelegate, this.onAccessFileCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap CreateChannel() {
            return new WebMethodsServiceSoapClientChannel(this);
        }
        
        private class WebMethodsServiceSoapClientChannel : ChannelBase<LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap>, LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap {
            
            public WebMethodsServiceSoapClientChannel(System.ServiceModel.ClientBase<LanSysWebGIS.WebMethodsService.WebMethodsServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDeleteFile(string path, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = path;
                System.IAsyncResult _result = base.BeginInvoke("DeleteFile", _args, callback, asyncState);
                return _result;
            }
            
            public string EndDeleteFile(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("DeleteFile", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDate(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetDate", _args, callback, asyncState);
                return _result;
            }
            
            public System.DateTime EndGetDate(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.DateTime _result = ((System.DateTime)(base.EndInvoke("GetDate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAccessFile(string path, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = path;
                System.IAsyncResult _result = base.BeginInvoke("AccessFile", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAccessFile(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AccessFile", _args, result);
            }
        }
    }
}
