//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanSysWebGIS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegistrationDataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistrationDataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanSysWebGIS.Web.Resources.RegistrationDataResources", typeof(RegistrationDataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور فعلی.
        /// </summary>
        public static string CurrentPasswordLabel {
            get {
                return ResourceManager.GetString("CurrentPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی،&lt;br&gt; &lt;br&gt;
        ///
        ///رمز عبور شما در سامانه WebGIS استانداری البرز با موفقیت تغییر یافت..
        /// </summary>
        public static string EmailBodyPasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("EmailBodyPasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی،&lt;br&gt;&lt;br&gt;
        ///رمز عبور شما در سامانه WebGIS استانداری البرز مجددا تنظیم شده است.&lt;br&gt;&lt;br&gt;
        ///رمز عبور جدید شما: &lt;b&gt;{0}&lt;/b&gt;
        ///&lt;br&gt;&lt;br&gt;
        ///
        ///لطفا در اولین ورود به سامانه، نسبت به تغییر رمز عبور خود اقدام نمائید..
        /// </summary>
        public static string EmailBodyPasswordResetSuccessfully {
            get {
                return ResourceManager.GetString("EmailBodyPasswordResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیک.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر رمز عبور.
        /// </summary>
        public static string EmailSubjectPasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("EmailSubjectPasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیم مجدد رمز عبور.
        /// </summary>
        public static string EmailSubjectPasswordResetSuccessfully {
            get {
                return ResourceManager.GetString("EmailSubjectPasswordResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;header&gt;&lt;/header&gt;
        ///&lt;body&gt;
        ///	&lt;table style=&quot;border:4px solid #015b9d;margin:0 auto;width:600px&quot; dir=&quot;rtl&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;600&quot; align=&quot;center&quot;&gt;
        ///		&lt;tbody&gt;
        ///			&lt;tr&gt;
        ///				&lt;td height=&quot;60&quot; align=&quot;center&quot; bgcolor=&quot;#015b9d&quot;&gt;&lt;a style=&quot;text-decoration:none;color:#ffffff&quot; href=&quot;http://webgis.p-alb.com&quot; target=&quot;_blank&quot;&gt;&lt;img src=&quot;http://91.98.96.246/header.gif&quot; style=&quot;padding-bottom: 20px;&quot;&gt; &lt;/a&gt; &lt;/td&gt;
        ///			&lt;/tr&gt;
        ///			&lt;tr&gt;
        ///				&lt;td bgcolor=&quot;#e0e0e0&quot;&gt;
        ///					&lt;table style=&quot;padding:3px [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailTemplate {
            get {
                return ResourceManager.GetString("EmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام دلخواهی که می خواهید در این سیستم نمایش داده شود.
        /// </summary>
        public static string FriendlyNameDescription {
            get {
                return ResourceManager.GetString("FriendlyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام دلخواه.
        /// </summary>
        public static string FriendlyNameLabel {
            get {
                return ResourceManager.GetString("FriendlyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائید رمز عبور جدید.
        /// </summary>
        public static string NewPasswordConfirmationLabel {
            get {
                return ResourceManager.GetString("NewPasswordConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اداره.
        /// </summary>
        public static string OrganizationNameLabel {
            get {
                return ResourceManager.GetString("OrganizationNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائید رمز عبور.
        /// </summary>
        public static string PasswordConfirmationLabel {
            get {
                return ResourceManager.GetString("PasswordConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور باید حداقل 6 کاراکتر باشد.
        /// </summary>
        public static string PasswordDescription {
            get {
                return ResourceManager.GetString("PasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیم مجدد رمز عبور کاربر مورد نظر با موفقیت انجام شد.
        /// </summary>
        public static string ResetPasswordSuccessfullyMessage {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیم مجدد رمز عبور کاربر مورد نظر با مشکل مواجه شد.
        ///لطفا مجددا سعی نمائید.
        /// </summary>
        public static string ResetPasswordUnSuccessfullyMessage {
            get {
                return ResourceManager.GetString("ResetPasswordUnSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش.
        /// </summary>
        public static string RoleNameLabel {
            get {
                return ResourceManager.GetString("RoleNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ امنیتی.
        /// </summary>
        public static string SecurityAnswerLabel {
            get {
                return ResourceManager.GetString("SecurityAnswerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال امنیتی.
        /// </summary>
        public static string SecurityQuestionLabel {
            get {
                return ResourceManager.GetString("SecurityQuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string UserCommentLabel {
            get {
                return ResourceManager.GetString("UserCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string UserIDLabel {
            get {
                return ResourceManager.GetString("UserIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
    }
}
