//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanSysWebGIS.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanSysWebGIS.Assets.Resources.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already registered?.
        /// </summary>
        public static string AlreadyRegisteredLabel {
            get {
                return ResourceManager.GetString("AlreadyRegisteredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام برنامه.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی کلان مورد نظر و تمامی زیر مجموعه آن حذف می شوند.
        /// </summary>
        public static string AreYouSureMessageForRemoveDocTitle {
            get {
                return ResourceManager.GetString("AreYouSureMessageForRemoveDocTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف دسته بندی کلان.
        /// </summary>
        public static string AreYouSureTitleForRemoveDocTitle {
            get {
                return ResourceManager.GetString("AreYouSureTitleForRemoveDocTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authenticating....
        /// </summary>
        public static string AuthenticatingMessage {
            get {
                return ResourceManager.GetString("AuthenticatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Login.
        /// </summary>
        public static string BackToLoginButton {
            get {
                return ResourceManager.GetString("BackToLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ساخت کاربر جدید....
        /// </summary>
        public static string BusyIndicatorCreatingUser {
            get {
                return ResourceManager.GetString("BusyIndicatorCreatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بارگذاری اطلاعات....
        /// </summary>
        public static string BusyIndicatorLoadingData {
            get {
                return ResourceManager.GetString("BusyIndicatorLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کمی صبر کنید....
        /// </summary>
        public static string BusyIndicatorLoadingUser {
            get {
                return ResourceManager.GetString("BusyIndicatorLoadingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ورود....
        /// </summary>
        public static string BusyIndicatorLoggingIn {
            get {
                return ResourceManager.GetString("BusyIndicatorLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کمی صبر کنید....
        /// </summary>
        public static string BusyIndicatorRegisteringUser {
            get {
                return ResourceManager.GetString("BusyIndicatorRegisteringUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر رمز عبور.
        /// </summary>
        public static string ChangePasswordWindowTitle {
            get {
                return ResourceManager.GetString("ChangePasswordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاک کردن تمام فرم ها.
        /// </summary>
        public static string ClearForms {
            get {
                return ResourceManager.GetString("ClearForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تولید فرم ها.
        /// </summary>
        public static string CreateForms {
            get {
                return ResourceManager.GetString("CreateForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد کاربر جدید.
        /// </summary>
        public static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد کاربر جدید.
        /// </summary>
        public static string CreateUserWindowTitle {
            get {
                return ResourceManager.GetString("CreateUserWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف این کاربر اطمینان دارید؟.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش کاربر.
        /// </summary>
        public static string EditUserWindowTitle {
            get {
                return ResourceManager.GetString("EditUserWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرم ها و سطح دسترسی.
        /// </summary>
        public static string FormsAndAccess {
            get {
                return ResourceManager.GetString("FormsAndAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر میهمان.
        /// </summary>
        public static string GuestButton {
            get {
                return ResourceManager.GetString("GuestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما باید مجددا وارد سامانه شوید.
        /// </summary>
        public static string LoginAgainMessage {
            get {
                return ResourceManager.GetString("LoginAgainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string LogOffButton {
            get {
                return ResourceManager.GetString("LogOffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت گروههای کاربری.
        /// </summary>
        public static string ManageRoles {
            get {
                return ResourceManager.GetString("ManageRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کاربران.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از پاک کردن این رکورد مطمئن هستید؟.
        /// </summary>
        public static string msgAreYouSureToDeleteRecord {
            get {
                return ResourceManager.GetString("msgAreYouSureToDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل با موفقیت ذخیره شد.
        /// </summary>
        public static string msgFileSaved {
            get {
                return ResourceManager.GetString("msgFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجرای سرویس نقشه با خطا مواجه شد.
        /// </summary>
        public static string msgMapInitFailed {
            get {
                return ResourceManager.GetString("msgMapInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهمان گرامی امکان استفاده از ابزار مورد نظر برای شما وجود ندارد.
        /// </summary>
        public static string msgNotAvailable {
            get {
                return ResourceManager.GetString("msgNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجوز لازم برای انجام عملیات مورد نظر را ندارید.
        /// </summary>
        public static string msgNotProperAccessLevel {
            get {
                return ResourceManager.GetString("msgNotProperAccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عارضه ای با مشخصات مورد نظر یافت نشد.
        /// </summary>
        public static string msgQueryBuilderNoFeatureFound {
            get {
                return ResourceManager.GetString("msgQueryBuilderNoFeatureFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو با خطا مواجه شد.
        /// </summary>
        public static string msgQueryFailed {
            get {
                return ResourceManager.GetString("msgQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو نتیجه ای در برنداشت.
        /// </summary>
        public static string msgQueryHasNoOutput {
            get {
                return ResourceManager.GetString("msgQueryHasNoOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد با موفقیت در پایگاه داده ذخیره شد.
        /// </summary>
        public static string msgRecordStoredSuccessfully {
            get {
                return ResourceManager.GetString("msgRecordStoredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا حداقل یکی از لایه ها را انتخاب کنید.
        /// </summary>
        public static string msgSelectAtLeastOneLayer {
            get {
                return ResourceManager.GetString("msgSelectAtLeastOneLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب عارضه با خطا مواجه شد.
        /// </summary>
        public static string msgSelectFeatureFailed {
            get {
                return ResourceManager.GetString("msgSelectFeatureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر محترم، متاسفانه فایل انتخاب شده از استاندارد یونیکد استفاده نمی کند.
        /// </summary>
        public static string msgViewShp1 {
            get {
                return ResourceManager.GetString("msgViewShp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا هر دو فایل مورد نیاز را وارد کنید\n(shp,dbf).
        /// </summary>
        public static string msgViewShp2 {
            get {
                return ResourceManager.GetString("msgViewShp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !داده ها با موفقیت به نقشه اضافه شد\nاگر داده ها در موقعیت صحیح قرار نگرفته اند، لطفا قبل از بارگذاری داده ها، ابتدا سیستم مختصات آنها را به سیستم مختصات زیر تغییر دهید\nWGS_1984_Web_Mercator_Auxiliary_Sphere (wkid:3857).
        /// </summary>
        public static string msgViewShp3 {
            get {
                return ResourceManager.GetString("msgViewShp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنوز ثبت نام نکرده اید؟.
        /// </summary>
        public static string NotRegisteredYetLabel {
            get {
                return ResourceManager.GetString("NotRegisteredYetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائید.
        /// </summary>
        public static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور با موفقیت تغییر یافت.
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر رمز عبور با موفقیت انجام نشد. لطفا مجددا تلاش نمایید.
        /// </summary>
        public static string PasswordChangedUnSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedUnSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        public static string RegisterNowButton {
            get {
                return ResourceManager.GetString("RegisterNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تمام فیلدهای الزامی را برای ایجاد کاربر جدید پر کنید.
        /// </summary>
        public static string RegistrationFormHeader {
            get {
                return ResourceManager.GetString("RegistrationFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegistrationWindowTitle {
            get {
                return ResourceManager.GetString("RegistrationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من را در حالت ورود نگه دار.
        /// </summary>
        public static string RememberMeLabel {
            get {
                return ResourceManager.GetString("RememberMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیم مجدد رمز عبور.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از تنظیم مجدد رمز عبور این کاربر اطمینان دارید؟.
        /// </summary>
        public static string ResetPasswordAsk {
            get {
                return ResourceManager.GetString("ResetPasswordAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه کاربری.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروههای کاربری.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو بوسیله.
        /// </summary>
        public static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی کاربران در گروه کاربری.
        /// </summary>
        public static string SearchForRoles {
            get {
                return ResourceManager.GetString("SearchForRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی کاربران.
        /// </summary>
        public static string SearchForUsers {
            get {
                return ResourceManager.GetString("SearchForUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی کاربران آنلاین بوسیله گروه کاربری.
        /// </summary>
        public static string SearchOnlineUsersByRole {
            get {
                return ResourceManager.GetString("SearchOnlineUsersByRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش لاگ.
        /// </summary>
        public static string ShowLog {
            get {
                return ResourceManager.GetString("ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش کاربران آنلاین.
        /// </summary>
        public static string ShowOnlineUsers {
            get {
                return ResourceManager.GetString("ShowOnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیغام سامانه.
        /// </summary>
        public static string SystemMessage {
            get {
                return ResourceManager.GetString("SystemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کاربری.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت کاربران.
        /// </summary>
        public static string UsersStatusLabel {
            get {
                return ResourceManager.GetString("UsersStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوش‌آمدید {0}.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
