//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanSysWebGIS.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanSysWebGIS.Assets.Resources.ErrorResources", typeof(ErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای تغییر رمز عبور ابتدا باید با نام کاربری خود وارد سامانه شوید.
        /// </summary>
        public static string ChangePassException {
            get {
                return ResourceManager.GetString("ChangePassException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیج ترسیمی انجام نشده است.
        /// </summary>
        public static string ClearDrawingError {
            get {
                return ResourceManager.GetString("ClearDrawingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای پست الکترونیکی وارد شده، یک کاربر موجود است. لطفا پست الکترونیکی دیگری وارد کنید.
        /// </summary>
        public static string CreateUserStatusDuplicateEmail {
            get {
                return ResourceManager.GetString("CreateUserStatusDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نام کاربری قبلا ایجاد شده است. لطفا نام کاربری دیگری وارد کنید.
        /// </summary>
        public static string CreateUserStatusDuplicateUserName {
            get {
                return ResourceManager.GetString("CreateUserStatusDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string CreateUserStatusFailed {
            get {
                return ResourceManager.GetString("CreateUserStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور فعلی صحیح نیست.
        /// </summary>
        public static string ErrorBadPassword {
            get {
                return ResourceManager.GetString("ErrorBadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور صحیح نیست.
        /// </summary>
        public static string ErrorBadUserNameOrPassword {
            get {
                return ResourceManager.GetString("ErrorBadUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration was successful but there was a problem while trying to log in with your credentials: {0}.
        /// </summary>
        public static string ErrorLoginAfterRegistrationFailed {
            get {
                return ResourceManager.GetString("ErrorLoginAfterRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات خطا.
        /// </summary>
        public static string ErrorWindowErrorDetails {
            get {
                return ResourceManager.GetString("ErrorWindowErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک خطای ناشناخته در سیستم رخ داده است. برای راهنمایی بیشتر با مدیر سیستم تماس بگیرید.
        /// </summary>
        public static string ErrorWindowGenericError {
            get {
                return ResourceManager.GetString("ErrorWindowGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caused by: {0}.
        /// </summary>
        public static string ErrorWindowInnerException {
            get {
                return ResourceManager.GetString("ErrorWindowInnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string ErrorWindowTitle {
            get {
                return ResourceManager.GetString("ErrorWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات هندسی مورد نظر با خطا مواجه شد.
        /// </summary>
        public static string GeometryServiceFailed {
            get {
                return ResourceManager.GetString("GeometryServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا شماره زون و هر دو مولفه مختصاتی را وارد نمایید.
        /// </summary>
        public static string GoToXYError {
            get {
                return ResourceManager.GetString("GoToXYError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مختصات وارد شده نامعتبر است.
        /// </summary>
        public static string InvalidInputCoor {
            get {
                return ResourceManager.GetString("InvalidInputCoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زون را با فرمت &quot;شماره زون + شمالی/جنوبی&quot; وارد کنید مانند &quot;39N&quot;.
        /// </summary>
        public static string ZoneIsNorthError {
            get {
                return ResourceManager.GetString("ZoneIsNorthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا حداقل یک عارضه را انتخاب نمایید.
        /// </summary>
        public static string ZoomToFeature {
            get {
                return ResourceManager.GetString("ZoomToFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مختصات وارد شده صحیح نمی باشد.
        /// </summary>
        public static string ZoomToXYError {
            get {
                return ResourceManager.GetString("ZoomToXYError", resourceCulture);
            }
        }
    }
}
