//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanSysWebGIS.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeoMapsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeoMapsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanSysWebGIS.Assets.Resources.GeoMapsStrings", typeof(GeoMapsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های موجود.
        /// </summary>
        public static string AvailableData {
            get {
                return ResourceManager.GetString("AvailableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این قالب چاپ، برای محدوده انتخاب شده قابل استفاده نیست. لطفا محدوده دیگری را انتخاب کنید..
        /// </summary>
        public static string BadPrintingExtentError {
            get {
                return ResourceManager.GetString("BadPrintingExtentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این قالب چاپ، برای اندکس انتخاب شده قابل استفاده نیست. لطفا قالب دیگری را انتخاب کنید..
        /// </summary>
        public static string BadPrintingTemplateError {
            get {
                return ResourceManager.GetString("BadPrintingTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاکسازی.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر روی نقشه کلیک کنید.
        /// </summary>
        public static string ClickOnMap {
            get {
                return ResourceManager.GetString("ClickOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چک کردن موجودی داده برای اندکس های ترکیبی امکان پذیر نیست.
        /// </summary>
        public static string DataAvailabilityError {
            get {
                return ResourceManager.GetString("DataAvailabilityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشه زمین مرجع.
        /// </summary>
        public static string GeoReference {
            get {
                return ResourceManager.GetString("GeoReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش اندکس های جستجو شده.
        /// </summary>
        public static string GraphicsLayer {
            get {
                return ResourceManager.GetString("GraphicsLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ عارضه ای انتخاب نشده است.
        /// </summary>
        public static string NoFeatureSelected {
            get {
                return ResourceManager.GetString("NoFeatureSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشه اسکن شده.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو بوسیله نام نقشه برای اندکس های ترکیبی امکان پذیر نیست.
        /// </summary>
        public static string SearchMapNameError {
            get {
                return ResourceManager.GetString("SearchMapNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو بوسیله شماره نقشه برای اندکس های ترکیبی امکان پذیر نیست.
        /// </summary>
        public static string SearchMapNumberError {
            get {
                return ResourceManager.GetString("SearchMapNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده رقومی.
        /// </summary>
        public static string Shapefile {
            get {
                return ResourceManager.GetString("Shapefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نقشه.
        /// </summary>
        public static string SheetName {
            get {
                return ResourceManager.GetString("SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره نقشه.
        /// </summary>
        public static string SheetNo {
            get {
                return ResourceManager.GetString("SheetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش اسناد مرتبط.
        /// </summary>
        public static string ShowRelatedDocuments {
            get {
                return ResourceManager.GetString("ShowRelatedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فراخوانی داده ها به درستی انجام نشد.
        /// </summary>
        public static string SpatialServiceError {
            get {
                return ResourceManager.GetString("SpatialServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بزرگنمایی.
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
