//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace LanSysWebGIS.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GeoMapsDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GeoMapsDBEntities object using the connection string found in the 'GeoMapsDBEntities' section of the application configuration file.
        /// </summary>
        public GeoMapsDBEntities() : base("name=GeoMapsDBEntities", "GeoMapsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GeoMapsDBEntities object.
        /// </summary>
        public GeoMapsDBEntities(string connectionString) : base(connectionString, "GeoMapsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GeoMapsDBEntities object.
        /// </summary>
        public GeoMapsDBEntities(EntityConnection connection) : base(connection, "GeoMapsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LayersWithDoc> LayersWithDoc
        {
            get
            {
                if ((_LayersWithDoc == null))
                {
                    _LayersWithDoc = base.CreateObjectSet<LayersWithDoc>("LayersWithDoc");
                }
                return _LayersWithDoc;
            }
        }
        private ObjectSet<LayersWithDoc> _LayersWithDoc;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LayersWithDoc EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLayersWithDoc(LayersWithDoc layersWithDoc)
        {
            base.AddObject("LayersWithDoc", layersWithDoc);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public int ClearSelectedLayers()
        {
            return base.ExecuteFunction("ClearSelectedLayers");
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GeoMapsDBModel", Name="LayersWithDoc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LayersWithDoc : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LayersWithDoc object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static LayersWithDoc CreateLayersWithDoc(global::System.Int32 id)
        {
            LayersWithDoc layersWithDoc = new LayersWithDoc();
            layersWithDoc.Id = id;
            return layersWithDoc;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LayerName
        {
            get
            {
                return _LayerName;
            }
            set
            {
                OnLayerNameChanging(value);
                ReportPropertyChanging("LayerName");
                _LayerName = StructuralObject.SetValidValue(value, true, "LayerName");
                ReportPropertyChanged("LayerName");
                OnLayerNameChanged();
            }
        }
        private global::System.String _LayerName;
        partial void OnLayerNameChanging(global::System.String value);
        partial void OnLayerNameChanged();

        #endregion

    }

    #endregion

}
