//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace LanSysWebGIS.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ViewEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ViewEntities object using the connection string found in the 'ViewEntities' section of the application configuration file.
        /// </summary>
        public ViewEntities() : base("name=ViewEntities", "ViewEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ViewEntities object.
        /// </summary>
        public ViewEntities(string connectionString) : base(connectionString, "ViewEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ViewEntities object.
        /// </summary>
        public ViewEntities(EntityConnection connection) : base(connection, "ViewEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwJamiat_Block> vwJamiat_Block
        {
            get
            {
                if ((_vwJamiat_Block == null))
                {
                    _vwJamiat_Block = base.CreateObjectSet<vwJamiat_Block>("vwJamiat_Block");
                }
                return _vwJamiat_Block;
            }
        }
        private ObjectSet<vwJamiat_Block> _vwJamiat_Block;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwJamiat_Eghamat> vwJamiat_Eghamat
        {
            get
            {
                if ((_vwJamiat_Eghamat == null))
                {
                    _vwJamiat_Eghamat = base.CreateObjectSet<vwJamiat_Eghamat>("vwJamiat_Eghamat");
                }
                return _vwJamiat_Eghamat;
            }
        }
        private ObjectSet<vwJamiat_Eghamat> _vwJamiat_Eghamat;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwJamiat_Jensiat> vwJamiat_Jensiat
        {
            get
            {
                if ((_vwJamiat_Jensiat == null))
                {
                    _vwJamiat_Jensiat = base.CreateObjectSet<vwJamiat_Jensiat>("vwJamiat_Jensiat");
                }
                return _vwJamiat_Jensiat;
            }
        }
        private ObjectSet<vwJamiat_Jensiat> _vwJamiat_Jensiat;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwJamiat_MahaleKarYaTahsil> vwJamiat_MahaleKarYaTahsil
        {
            get
            {
                if ((_vwJamiat_MahaleKarYaTahsil == null))
                {
                    _vwJamiat_MahaleKarYaTahsil = base.CreateObjectSet<vwJamiat_MahaleKarYaTahsil>("vwJamiat_MahaleKarYaTahsil");
                }
                return _vwJamiat_MahaleKarYaTahsil;
            }
        }
        private ObjectSet<vwJamiat_MahaleKarYaTahsil> _vwJamiat_MahaleKarYaTahsil;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwJamiat_MahaleTavalod> vwJamiat_MahaleTavalod
        {
            get
            {
                if ((_vwJamiat_MahaleTavalod == null))
                {
                    _vwJamiat_MahaleTavalod = base.CreateObjectSet<vwJamiat_MahaleTavalod>("vwJamiat_MahaleTavalod");
                }
                return _vwJamiat_MahaleTavalod;
            }
        }
        private ObjectSet<vwJamiat_MahaleTavalod> _vwJamiat_MahaleTavalod;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwJamiat_savad> vwJamiat_savad
        {
            get
            {
                if ((_vwJamiat_savad == null))
                {
                    _vwJamiat_savad = base.CreateObjectSet<vwJamiat_savad>("vwJamiat_savad");
                }
                return _vwJamiat_savad;
            }
        }
        private ObjectSet<vwJamiat_savad> _vwJamiat_savad;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwJamiat_ShahrYaDehestan> vwJamiat_ShahrYaDehestan
        {
            get
            {
                if ((_vwJamiat_ShahrYaDehestan == null))
                {
                    _vwJamiat_ShahrYaDehestan = base.CreateObjectSet<vwJamiat_ShahrYaDehestan>("vwJamiat_ShahrYaDehestan");
                }
                return _vwJamiat_ShahrYaDehestan;
            }
        }
        private ObjectSet<vwJamiat_ShahrYaDehestan> _vwJamiat_ShahrYaDehestan;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwJamiat_Shoghl> vwJamiat_Shoghl
        {
            get
            {
                if ((_vwJamiat_Shoghl == null))
                {
                    _vwJamiat_Shoghl = base.CreateObjectSet<vwJamiat_Shoghl>("vwJamiat_Shoghl");
                }
                return _vwJamiat_Shoghl;
            }
        }
        private ObjectSet<vwJamiat_Shoghl> _vwJamiat_Shoghl;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwJamiat_Taahol> vwJamiat_Taahol
        {
            get
            {
                if ((_vwJamiat_Taahol == null))
                {
                    _vwJamiat_Taahol = base.CreateObjectSet<vwJamiat_Taahol>("vwJamiat_Taahol");
                }
                return _vwJamiat_Taahol;
            }
        }
        private ObjectSet<vwJamiat_Taahol> _vwJamiat_Taahol;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwJamiatKol_Sen> vwJamiatKol_Sen
        {
            get
            {
                if ((_vwJamiatKol_Sen == null))
                {
                    _vwJamiatKol_Sen = base.CreateObjectSet<vwJamiatKol_Sen>("vwJamiatKol_Sen");
                }
                return _vwJamiatKol_Sen;
            }
        }
        private ObjectSet<vwJamiatKol_Sen> _vwJamiatKol_Sen;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwJamiatMard_Sen> vwJamiatMard_Sen
        {
            get
            {
                if ((_vwJamiatMard_Sen == null))
                {
                    _vwJamiatMard_Sen = base.CreateObjectSet<vwJamiatMard_Sen>("vwJamiatMard_Sen");
                }
                return _vwJamiatMard_Sen;
            }
        }
        private ObjectSet<vwJamiatMard_Sen> _vwJamiatMard_Sen;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwJamiatZan_Sen> vwJamiatZan_Sen
        {
            get
            {
                if ((_vwJamiatZan_Sen == null))
                {
                    _vwJamiatZan_Sen = base.CreateObjectSet<vwJamiatZan_Sen>("vwJamiatZan_Sen");
                }
                return _vwJamiatZan_Sen;
            }
        }
        private ObjectSet<vwJamiatZan_Sen> _vwJamiatZan_Sen;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwKhanevar_ShahryaDehestan> vwKhanevar_ShahryaDehestan
        {
            get
            {
                if ((_vwKhanevar_ShahryaDehestan == null))
                {
                    _vwKhanevar_ShahryaDehestan = base.CreateObjectSet<vwKhanevar_ShahryaDehestan>("vwKhanevar_ShahryaDehestan");
                }
                return _vwKhanevar_ShahryaDehestan;
            }
        }
        private ObjectSet<vwKhanevar_ShahryaDehestan> _vwKhanevar_ShahryaDehestan;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwMasahatZirBana> vwMasahatZirBana
        {
            get
            {
                if ((_vwMasahatZirBana == null))
                {
                    _vwMasahatZirBana = base.CreateObjectSet<vwMasahatZirBana>("vwMasahatZirBana");
                }
                return _vwMasahatZirBana;
            }
        }
        private ObjectSet<vwMasahatZirBana> _vwMasahatZirBana;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwJamiat_Block EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwJamiat_Block(vwJamiat_Block vwJamiat_Block)
        {
            base.AddObject("vwJamiat_Block", vwJamiat_Block);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwJamiat_Eghamat EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwJamiat_Eghamat(vwJamiat_Eghamat vwJamiat_Eghamat)
        {
            base.AddObject("vwJamiat_Eghamat", vwJamiat_Eghamat);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwJamiat_Jensiat EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwJamiat_Jensiat(vwJamiat_Jensiat vwJamiat_Jensiat)
        {
            base.AddObject("vwJamiat_Jensiat", vwJamiat_Jensiat);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwJamiat_MahaleKarYaTahsil EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwJamiat_MahaleKarYaTahsil(vwJamiat_MahaleKarYaTahsil vwJamiat_MahaleKarYaTahsil)
        {
            base.AddObject("vwJamiat_MahaleKarYaTahsil", vwJamiat_MahaleKarYaTahsil);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwJamiat_MahaleTavalod EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwJamiat_MahaleTavalod(vwJamiat_MahaleTavalod vwJamiat_MahaleTavalod)
        {
            base.AddObject("vwJamiat_MahaleTavalod", vwJamiat_MahaleTavalod);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwJamiat_savad EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwJamiat_savad(vwJamiat_savad vwJamiat_savad)
        {
            base.AddObject("vwJamiat_savad", vwJamiat_savad);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwJamiat_ShahrYaDehestan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwJamiat_ShahrYaDehestan(vwJamiat_ShahrYaDehestan vwJamiat_ShahrYaDehestan)
        {
            base.AddObject("vwJamiat_ShahrYaDehestan", vwJamiat_ShahrYaDehestan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwJamiat_Shoghl EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwJamiat_Shoghl(vwJamiat_Shoghl vwJamiat_Shoghl)
        {
            base.AddObject("vwJamiat_Shoghl", vwJamiat_Shoghl);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwJamiat_Taahol EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwJamiat_Taahol(vwJamiat_Taahol vwJamiat_Taahol)
        {
            base.AddObject("vwJamiat_Taahol", vwJamiat_Taahol);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwJamiatKol_Sen EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwJamiatKol_Sen(vwJamiatKol_Sen vwJamiatKol_Sen)
        {
            base.AddObject("vwJamiatKol_Sen", vwJamiatKol_Sen);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwJamiatMard_Sen EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwJamiatMard_Sen(vwJamiatMard_Sen vwJamiatMard_Sen)
        {
            base.AddObject("vwJamiatMard_Sen", vwJamiatMard_Sen);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwJamiatZan_Sen EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwJamiatZan_Sen(vwJamiatZan_Sen vwJamiatZan_Sen)
        {
            base.AddObject("vwJamiatZan_Sen", vwJamiatZan_Sen);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwKhanevar_ShahryaDehestan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwKhanevar_ShahryaDehestan(vwKhanevar_ShahryaDehestan vwKhanevar_ShahryaDehestan)
        {
            base.AddObject("vwKhanevar_ShahryaDehestan", vwKhanevar_ShahryaDehestan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwMasahatZirBana EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwMasahatZirBana(vwMasahatZirBana vwMasahatZirBana)
        {
            base.AddObject("vwMasahatZirBana", vwMasahatZirBana);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ViewModel", Name="vwJamiat_Block")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwJamiat_Block : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwJamiat_Block object.
        /// </summary>
        /// <param name="ident">Initial value of the Ident property.</param>
        public static vwJamiat_Block CreatevwJamiat_Block(global::System.String ident)
        {
            vwJamiat_Block vwJamiat_Block = new vwJamiat_Block();
            vwJamiat_Block.Ident = ident;
            return vwJamiat_Block;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ident
        {
            get
            {
                return _Ident;
            }
            set
            {
                if (_Ident != value)
                {
                    OnIdentChanging(value);
                    ReportPropertyChanging("Ident");
                    _Ident = StructuralObject.SetValidValue(value, false, "Ident");
                    ReportPropertyChanged("Ident");
                    OnIdentChanged();
                }
            }
        }
        private global::System.String _Ident;
        partial void OnIdentChanging(global::System.String value);
        partial void OnIdentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String X_Value
        {
            get
            {
                return _X_Value;
            }
            set
            {
                OnX_ValueChanging(value);
                ReportPropertyChanging("X_Value");
                _X_Value = StructuralObject.SetValidValue(value, true, "X_Value");
                ReportPropertyChanged("X_Value");
                OnX_ValueChanged();
            }
        }
        private global::System.String _X_Value;
        partial void OnX_ValueChanging(global::System.String value);
        partial void OnX_ValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y_Value
        {
            get
            {
                return _Y_Value;
            }
            set
            {
                OnY_ValueChanging(value);
                ReportPropertyChanging("Y_Value");
                _Y_Value = StructuralObject.SetValidValue(value, "Y_Value");
                ReportPropertyChanged("Y_Value");
                OnY_ValueChanged();
            }
        }
        private Nullable<global::System.Double> _Y_Value;
        partial void OnY_ValueChanging(Nullable<global::System.Double> value);
        partial void OnY_ValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ViewModel", Name="vwJamiat_Eghamat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwJamiat_Eghamat : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwJamiat_Eghamat object.
        /// </summary>
        /// <param name="x_Value">Initial value of the X_Value property.</param>
        public static vwJamiat_Eghamat CreatevwJamiat_Eghamat(global::System.String x_Value)
        {
            vwJamiat_Eghamat vwJamiat_Eghamat = new vwJamiat_Eghamat();
            vwJamiat_Eghamat.X_Value = x_Value;
            return vwJamiat_Eghamat;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y_Value
        {
            get
            {
                return _Y_Value;
            }
            set
            {
                OnY_ValueChanging(value);
                ReportPropertyChanging("Y_Value");
                _Y_Value = StructuralObject.SetValidValue(value, "Y_Value");
                ReportPropertyChanged("Y_Value");
                OnY_ValueChanged();
            }
        }
        private Nullable<global::System.Double> _Y_Value;
        partial void OnY_ValueChanging(Nullable<global::System.Double> value);
        partial void OnY_ValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String X_Value
        {
            get
            {
                return _X_Value;
            }
            set
            {
                if (_X_Value != value)
                {
                    OnX_ValueChanging(value);
                    ReportPropertyChanging("X_Value");
                    _X_Value = StructuralObject.SetValidValue(value, false, "X_Value");
                    ReportPropertyChanged("X_Value");
                    OnX_ValueChanged();
                }
            }
        }
        private global::System.String _X_Value;
        partial void OnX_ValueChanging(global::System.String value);
        partial void OnX_ValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ViewModel", Name="vwJamiat_Jensiat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwJamiat_Jensiat : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwJamiat_Jensiat object.
        /// </summary>
        /// <param name="x_Value">Initial value of the X_Value property.</param>
        public static vwJamiat_Jensiat CreatevwJamiat_Jensiat(global::System.String x_Value)
        {
            vwJamiat_Jensiat vwJamiat_Jensiat = new vwJamiat_Jensiat();
            vwJamiat_Jensiat.X_Value = x_Value;
            return vwJamiat_Jensiat;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y_Value
        {
            get
            {
                return _Y_Value;
            }
            set
            {
                OnY_ValueChanging(value);
                ReportPropertyChanging("Y_Value");
                _Y_Value = StructuralObject.SetValidValue(value, "Y_Value");
                ReportPropertyChanged("Y_Value");
                OnY_ValueChanged();
            }
        }
        private Nullable<global::System.Double> _Y_Value;
        partial void OnY_ValueChanging(Nullable<global::System.Double> value);
        partial void OnY_ValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String X_Value
        {
            get
            {
                return _X_Value;
            }
            set
            {
                if (_X_Value != value)
                {
                    OnX_ValueChanging(value);
                    ReportPropertyChanging("X_Value");
                    _X_Value = StructuralObject.SetValidValue(value, false, "X_Value");
                    ReportPropertyChanged("X_Value");
                    OnX_ValueChanged();
                }
            }
        }
        private global::System.String _X_Value;
        partial void OnX_ValueChanging(global::System.String value);
        partial void OnX_ValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ViewModel", Name="vwJamiat_MahaleKarYaTahsil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwJamiat_MahaleKarYaTahsil : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwJamiat_MahaleKarYaTahsil object.
        /// </summary>
        /// <param name="x_Value">Initial value of the X_Value property.</param>
        public static vwJamiat_MahaleKarYaTahsil CreatevwJamiat_MahaleKarYaTahsil(global::System.String x_Value)
        {
            vwJamiat_MahaleKarYaTahsil vwJamiat_MahaleKarYaTahsil = new vwJamiat_MahaleKarYaTahsil();
            vwJamiat_MahaleKarYaTahsil.X_Value = x_Value;
            return vwJamiat_MahaleKarYaTahsil;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y_Value
        {
            get
            {
                return _Y_Value;
            }
            set
            {
                OnY_ValueChanging(value);
                ReportPropertyChanging("Y_Value");
                _Y_Value = StructuralObject.SetValidValue(value, "Y_Value");
                ReportPropertyChanged("Y_Value");
                OnY_ValueChanged();
            }
        }
        private Nullable<global::System.Double> _Y_Value;
        partial void OnY_ValueChanging(Nullable<global::System.Double> value);
        partial void OnY_ValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String X_Value
        {
            get
            {
                return _X_Value;
            }
            set
            {
                if (_X_Value != value)
                {
                    OnX_ValueChanging(value);
                    ReportPropertyChanging("X_Value");
                    _X_Value = StructuralObject.SetValidValue(value, false, "X_Value");
                    ReportPropertyChanged("X_Value");
                    OnX_ValueChanged();
                }
            }
        }
        private global::System.String _X_Value;
        partial void OnX_ValueChanging(global::System.String value);
        partial void OnX_ValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ViewModel", Name="vwJamiat_MahaleTavalod")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwJamiat_MahaleTavalod : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwJamiat_MahaleTavalod object.
        /// </summary>
        /// <param name="x_Value">Initial value of the X_Value property.</param>
        public static vwJamiat_MahaleTavalod CreatevwJamiat_MahaleTavalod(global::System.String x_Value)
        {
            vwJamiat_MahaleTavalod vwJamiat_MahaleTavalod = new vwJamiat_MahaleTavalod();
            vwJamiat_MahaleTavalod.X_Value = x_Value;
            return vwJamiat_MahaleTavalod;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y_Value
        {
            get
            {
                return _Y_Value;
            }
            set
            {
                OnY_ValueChanging(value);
                ReportPropertyChanging("Y_Value");
                _Y_Value = StructuralObject.SetValidValue(value, "Y_Value");
                ReportPropertyChanged("Y_Value");
                OnY_ValueChanged();
            }
        }
        private Nullable<global::System.Double> _Y_Value;
        partial void OnY_ValueChanging(Nullable<global::System.Double> value);
        partial void OnY_ValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String X_Value
        {
            get
            {
                return _X_Value;
            }
            set
            {
                if (_X_Value != value)
                {
                    OnX_ValueChanging(value);
                    ReportPropertyChanging("X_Value");
                    _X_Value = StructuralObject.SetValidValue(value, false, "X_Value");
                    ReportPropertyChanged("X_Value");
                    OnX_ValueChanged();
                }
            }
        }
        private global::System.String _X_Value;
        partial void OnX_ValueChanging(global::System.String value);
        partial void OnX_ValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ViewModel", Name="vwJamiat_savad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwJamiat_savad : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwJamiat_savad object.
        /// </summary>
        /// <param name="x_Value">Initial value of the X_Value property.</param>
        public static vwJamiat_savad CreatevwJamiat_savad(global::System.String x_Value)
        {
            vwJamiat_savad vwJamiat_savad = new vwJamiat_savad();
            vwJamiat_savad.X_Value = x_Value;
            return vwJamiat_savad;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y_Value
        {
            get
            {
                return _Y_Value;
            }
            set
            {
                OnY_ValueChanging(value);
                ReportPropertyChanging("Y_Value");
                _Y_Value = StructuralObject.SetValidValue(value, "Y_Value");
                ReportPropertyChanged("Y_Value");
                OnY_ValueChanged();
            }
        }
        private Nullable<global::System.Double> _Y_Value;
        partial void OnY_ValueChanging(Nullable<global::System.Double> value);
        partial void OnY_ValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String X_Value
        {
            get
            {
                return _X_Value;
            }
            set
            {
                if (_X_Value != value)
                {
                    OnX_ValueChanging(value);
                    ReportPropertyChanging("X_Value");
                    _X_Value = StructuralObject.SetValidValue(value, false, "X_Value");
                    ReportPropertyChanged("X_Value");
                    OnX_ValueChanged();
                }
            }
        }
        private global::System.String _X_Value;
        partial void OnX_ValueChanging(global::System.String value);
        partial void OnX_ValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ViewModel", Name="vwJamiat_ShahrYaDehestan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwJamiat_ShahrYaDehestan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwJamiat_ShahrYaDehestan object.
        /// </summary>
        /// <param name="ident">Initial value of the Ident property.</param>
        public static vwJamiat_ShahrYaDehestan CreatevwJamiat_ShahrYaDehestan(global::System.String ident)
        {
            vwJamiat_ShahrYaDehestan vwJamiat_ShahrYaDehestan = new vwJamiat_ShahrYaDehestan();
            vwJamiat_ShahrYaDehestan.Ident = ident;
            return vwJamiat_ShahrYaDehestan;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ident
        {
            get
            {
                return _Ident;
            }
            set
            {
                if (_Ident != value)
                {
                    OnIdentChanging(value);
                    ReportPropertyChanging("Ident");
                    _Ident = StructuralObject.SetValidValue(value, false, "Ident");
                    ReportPropertyChanged("Ident");
                    OnIdentChanged();
                }
            }
        }
        private global::System.String _Ident;
        partial void OnIdentChanging(global::System.String value);
        partial void OnIdentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y_Value
        {
            get
            {
                return _Y_Value;
            }
            set
            {
                OnY_ValueChanging(value);
                ReportPropertyChanging("Y_Value");
                _Y_Value = StructuralObject.SetValidValue(value, "Y_Value");
                ReportPropertyChanged("Y_Value");
                OnY_ValueChanged();
            }
        }
        private Nullable<global::System.Double> _Y_Value;
        partial void OnY_ValueChanging(Nullable<global::System.Double> value);
        partial void OnY_ValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String X_Value
        {
            get
            {
                return _X_Value;
            }
            set
            {
                OnX_ValueChanging(value);
                ReportPropertyChanging("X_Value");
                _X_Value = StructuralObject.SetValidValue(value, true, "X_Value");
                ReportPropertyChanged("X_Value");
                OnX_ValueChanged();
            }
        }
        private global::System.String _X_Value;
        partial void OnX_ValueChanging(global::System.String value);
        partial void OnX_ValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ViewModel", Name="vwJamiat_Shoghl")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwJamiat_Shoghl : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwJamiat_Shoghl object.
        /// </summary>
        /// <param name="x_Value">Initial value of the X_Value property.</param>
        public static vwJamiat_Shoghl CreatevwJamiat_Shoghl(global::System.String x_Value)
        {
            vwJamiat_Shoghl vwJamiat_Shoghl = new vwJamiat_Shoghl();
            vwJamiat_Shoghl.X_Value = x_Value;
            return vwJamiat_Shoghl;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y_Value
        {
            get
            {
                return _Y_Value;
            }
            set
            {
                OnY_ValueChanging(value);
                ReportPropertyChanging("Y_Value");
                _Y_Value = StructuralObject.SetValidValue(value, "Y_Value");
                ReportPropertyChanged("Y_Value");
                OnY_ValueChanged();
            }
        }
        private Nullable<global::System.Double> _Y_Value;
        partial void OnY_ValueChanging(Nullable<global::System.Double> value);
        partial void OnY_ValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String X_Value
        {
            get
            {
                return _X_Value;
            }
            set
            {
                if (_X_Value != value)
                {
                    OnX_ValueChanging(value);
                    ReportPropertyChanging("X_Value");
                    _X_Value = StructuralObject.SetValidValue(value, false, "X_Value");
                    ReportPropertyChanged("X_Value");
                    OnX_ValueChanged();
                }
            }
        }
        private global::System.String _X_Value;
        partial void OnX_ValueChanging(global::System.String value);
        partial void OnX_ValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ViewModel", Name="vwJamiat_Taahol")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwJamiat_Taahol : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwJamiat_Taahol object.
        /// </summary>
        /// <param name="x_Value">Initial value of the X_Value property.</param>
        public static vwJamiat_Taahol CreatevwJamiat_Taahol(global::System.String x_Value)
        {
            vwJamiat_Taahol vwJamiat_Taahol = new vwJamiat_Taahol();
            vwJamiat_Taahol.X_Value = x_Value;
            return vwJamiat_Taahol;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y_Value
        {
            get
            {
                return _Y_Value;
            }
            set
            {
                OnY_ValueChanging(value);
                ReportPropertyChanging("Y_Value");
                _Y_Value = StructuralObject.SetValidValue(value, "Y_Value");
                ReportPropertyChanged("Y_Value");
                OnY_ValueChanged();
            }
        }
        private Nullable<global::System.Double> _Y_Value;
        partial void OnY_ValueChanging(Nullable<global::System.Double> value);
        partial void OnY_ValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String X_Value
        {
            get
            {
                return _X_Value;
            }
            set
            {
                if (_X_Value != value)
                {
                    OnX_ValueChanging(value);
                    ReportPropertyChanging("X_Value");
                    _X_Value = StructuralObject.SetValidValue(value, false, "X_Value");
                    ReportPropertyChanged("X_Value");
                    OnX_ValueChanged();
                }
            }
        }
        private global::System.String _X_Value;
        partial void OnX_ValueChanging(global::System.String value);
        partial void OnX_ValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ViewModel", Name="vwJamiatKol_Sen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwJamiatKol_Sen : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwJamiatKol_Sen object.
        /// </summary>
        /// <param name="x_Value">Initial value of the X_Value property.</param>
        public static vwJamiatKol_Sen CreatevwJamiatKol_Sen(global::System.String x_Value)
        {
            vwJamiatKol_Sen vwJamiatKol_Sen = new vwJamiatKol_Sen();
            vwJamiatKol_Sen.X_Value = x_Value;
            return vwJamiatKol_Sen;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y_Value
        {
            get
            {
                return _Y_Value;
            }
            set
            {
                OnY_ValueChanging(value);
                ReportPropertyChanging("Y_Value");
                _Y_Value = StructuralObject.SetValidValue(value, "Y_Value");
                ReportPropertyChanged("Y_Value");
                OnY_ValueChanged();
            }
        }
        private Nullable<global::System.Double> _Y_Value;
        partial void OnY_ValueChanging(Nullable<global::System.Double> value);
        partial void OnY_ValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String X_Value
        {
            get
            {
                return _X_Value;
            }
            set
            {
                if (_X_Value != value)
                {
                    OnX_ValueChanging(value);
                    ReportPropertyChanging("X_Value");
                    _X_Value = StructuralObject.SetValidValue(value, false, "X_Value");
                    ReportPropertyChanged("X_Value");
                    OnX_ValueChanged();
                }
            }
        }
        private global::System.String _X_Value;
        partial void OnX_ValueChanging(global::System.String value);
        partial void OnX_ValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ViewModel", Name="vwJamiatMard_Sen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwJamiatMard_Sen : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwJamiatMard_Sen object.
        /// </summary>
        /// <param name="x_Value">Initial value of the X_Value property.</param>
        public static vwJamiatMard_Sen CreatevwJamiatMard_Sen(global::System.String x_Value)
        {
            vwJamiatMard_Sen vwJamiatMard_Sen = new vwJamiatMard_Sen();
            vwJamiatMard_Sen.X_Value = x_Value;
            return vwJamiatMard_Sen;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y_Value
        {
            get
            {
                return _Y_Value;
            }
            set
            {
                OnY_ValueChanging(value);
                ReportPropertyChanging("Y_Value");
                _Y_Value = StructuralObject.SetValidValue(value, "Y_Value");
                ReportPropertyChanged("Y_Value");
                OnY_ValueChanged();
            }
        }
        private Nullable<global::System.Double> _Y_Value;
        partial void OnY_ValueChanging(Nullable<global::System.Double> value);
        partial void OnY_ValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String X_Value
        {
            get
            {
                return _X_Value;
            }
            set
            {
                if (_X_Value != value)
                {
                    OnX_ValueChanging(value);
                    ReportPropertyChanging("X_Value");
                    _X_Value = StructuralObject.SetValidValue(value, false, "X_Value");
                    ReportPropertyChanged("X_Value");
                    OnX_ValueChanged();
                }
            }
        }
        private global::System.String _X_Value;
        partial void OnX_ValueChanging(global::System.String value);
        partial void OnX_ValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ViewModel", Name="vwJamiatZan_Sen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwJamiatZan_Sen : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwJamiatZan_Sen object.
        /// </summary>
        /// <param name="x_Value">Initial value of the X_Value property.</param>
        public static vwJamiatZan_Sen CreatevwJamiatZan_Sen(global::System.String x_Value)
        {
            vwJamiatZan_Sen vwJamiatZan_Sen = new vwJamiatZan_Sen();
            vwJamiatZan_Sen.X_Value = x_Value;
            return vwJamiatZan_Sen;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y_Value
        {
            get
            {
                return _Y_Value;
            }
            set
            {
                OnY_ValueChanging(value);
                ReportPropertyChanging("Y_Value");
                _Y_Value = StructuralObject.SetValidValue(value, "Y_Value");
                ReportPropertyChanged("Y_Value");
                OnY_ValueChanged();
            }
        }
        private Nullable<global::System.Double> _Y_Value;
        partial void OnY_ValueChanging(Nullable<global::System.Double> value);
        partial void OnY_ValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String X_Value
        {
            get
            {
                return _X_Value;
            }
            set
            {
                if (_X_Value != value)
                {
                    OnX_ValueChanging(value);
                    ReportPropertyChanging("X_Value");
                    _X_Value = StructuralObject.SetValidValue(value, false, "X_Value");
                    ReportPropertyChanged("X_Value");
                    OnX_ValueChanged();
                }
            }
        }
        private global::System.String _X_Value;
        partial void OnX_ValueChanging(global::System.String value);
        partial void OnX_ValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ViewModel", Name="vwKhanevar_ShahryaDehestan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwKhanevar_ShahryaDehestan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwKhanevar_ShahryaDehestan object.
        /// </summary>
        /// <param name="ident">Initial value of the Ident property.</param>
        public static vwKhanevar_ShahryaDehestan CreatevwKhanevar_ShahryaDehestan(global::System.String ident)
        {
            vwKhanevar_ShahryaDehestan vwKhanevar_ShahryaDehestan = new vwKhanevar_ShahryaDehestan();
            vwKhanevar_ShahryaDehestan.Ident = ident;
            return vwKhanevar_ShahryaDehestan;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ident
        {
            get
            {
                return _Ident;
            }
            set
            {
                if (_Ident != value)
                {
                    OnIdentChanging(value);
                    ReportPropertyChanging("Ident");
                    _Ident = StructuralObject.SetValidValue(value, false, "Ident");
                    ReportPropertyChanged("Ident");
                    OnIdentChanged();
                }
            }
        }
        private global::System.String _Ident;
        partial void OnIdentChanging(global::System.String value);
        partial void OnIdentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y_Value
        {
            get
            {
                return _Y_Value;
            }
            set
            {
                OnY_ValueChanging(value);
                ReportPropertyChanging("Y_Value");
                _Y_Value = StructuralObject.SetValidValue(value, "Y_Value");
                ReportPropertyChanged("Y_Value");
                OnY_ValueChanged();
            }
        }
        private Nullable<global::System.Double> _Y_Value;
        partial void OnY_ValueChanging(Nullable<global::System.Double> value);
        partial void OnY_ValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String X_Value
        {
            get
            {
                return _X_Value;
            }
            set
            {
                OnX_ValueChanging(value);
                ReportPropertyChanging("X_Value");
                _X_Value = StructuralObject.SetValidValue(value, true, "X_Value");
                ReportPropertyChanged("X_Value");
                OnX_ValueChanged();
            }
        }
        private global::System.String _X_Value;
        partial void OnX_ValueChanging(global::System.String value);
        partial void OnX_ValueChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ViewModel", Name="vwMasahatZirBana")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwMasahatZirBana : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwMasahatZirBana object.
        /// </summary>
        /// <param name="x_Value">Initial value of the X_Value property.</param>
        public static vwMasahatZirBana CreatevwMasahatZirBana(global::System.String x_Value)
        {
            vwMasahatZirBana vwMasahatZirBana = new vwMasahatZirBana();
            vwMasahatZirBana.X_Value = x_Value;
            return vwMasahatZirBana;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Y_Value
        {
            get
            {
                return _Y_Value;
            }
            set
            {
                OnY_ValueChanging(value);
                ReportPropertyChanging("Y_Value");
                _Y_Value = StructuralObject.SetValidValue(value, "Y_Value");
                ReportPropertyChanged("Y_Value");
                OnY_ValueChanged();
            }
        }
        private Nullable<global::System.Double> _Y_Value;
        partial void OnY_ValueChanging(Nullable<global::System.Double> value);
        partial void OnY_ValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String X_Value
        {
            get
            {
                return _X_Value;
            }
            set
            {
                if (_X_Value != value)
                {
                    OnX_ValueChanging(value);
                    ReportPropertyChanging("X_Value");
                    _X_Value = StructuralObject.SetValidValue(value, false, "X_Value");
                    ReportPropertyChanged("X_Value");
                    OnX_ValueChanged();
                }
            }
        }
        private global::System.String _X_Value;
        partial void OnX_ValueChanging(global::System.String value);
        partial void OnX_ValueChanged();

        #endregion

    }

    #endregion

}
